import mongoose, { Schema, type InferSchemaType, type Model } from "mongoose";

/**
 * One row per payment attempt. Created in `pending` state when the user starts
 * checkout; promoted to `success` only after server-side verification against
 * Paystack's API (popup callback OR webhook - whichever lands first wins).
 *
 * Lifecycle:
 *   pending  → success         (verified, grant issued)
 *   pending  → failed          (Paystack returned a failed transaction)
 *   pending  → abandoned       (Paystack says the customer did not complete)
 *   pending  → cancelled       (customer closed/cancelled the popup locally)
 *   pending  → expired         (attempt aged out without success)
 *   pending  → timeout         (Paystack verification timed out; retryable)
 *   pending  → ongoing/...     (Paystack says transaction is still in progress)
 *
 * The `paystackReference` is generated by us on init (so we can persist before
 * the network call) and echoed back to Paystack as `reference`. Unique index
 * is the idempotency anchor for verify + webhook.
 */
export const PAYMENT_STATUSES = [
  "pending",
  "success",
  "failed",
  "abandoned",
  "cancelled",
  "expired",
  "timeout",
  "ongoing",
  "processing",
  "queued",
  "reversed",
] as const;

export type PaymentStatus = (typeof PAYMENT_STATUSES)[number];

const paymentStatusHistorySchema = new Schema(
  {
    status: {
      type: String,
      enum: PAYMENT_STATUSES,
      required: true,
    },
    source: {
      type: String,
      enum: ["init", "popup", "verify", "webhook", "system"],
      required: true,
    },
    message: { type: String, default: null },
    paystackStatus: { type: String, default: null },
    at: { type: Date, default: () => new Date() },
  },
  { _id: false }
);

const paymentSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    templateId: {
      type: Schema.Types.ObjectId,
      ref: "Template",
      required: true,
      index: true,
    },
    // The user's working-design id (IndexedDB record id) - denormalised so
    // analytics can group "paid downloads of design X by user Y" without
    // joining IDB state. Optional so the schema doesn't lock us out of future
    // template-only purchases.
    userDesignId: { type: String, default: null },

    // Stored in kobo (Paystack's smallest unit). Converted to NGN at the
    // boundary. Centralises the precision discipline that prevents the
    // "100 NGN became 1.00 NGN" bug.
    amountKobo: { type: Number, required: true, min: 1 },
    currency: { type: String, default: "NGN" },

    // Our own reference, generated server-side at init. Globally unique.
    paystackReference: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    paystackAccessCode: { type: String, default: null },
    paystackAuthorizationUrl: { type: String, default: null },

    status: {
      type: String,
      enum: PAYMENT_STATUSES,
      default: "pending",
      required: true,
      index: true,
    },
    statusHistory: { type: [paymentStatusHistorySchema], default: [] },

    // The full Paystack verify payload - kept verbatim so reconciliation,
    // refund operations, and dispute handling have the original facts.
    providerResponse: { type: Schema.Types.Mixed, default: null },
    paystackStatus: { type: String, default: null },

    initializedAt: { type: Date, default: () => new Date() },
    expiresAt: { type: Date, default: null, index: true },
    lastVerifiedAt: { type: Date, default: null },
    paidAt: { type: Date, default: null },
    failedAt: { type: Date, default: null },
    cancelledAt: { type: Date, default: null },
    expiredAt: { type: Date, default: null },
    timedOutAt: { type: Date, default: null },
    failureReason: { type: String, default: null },
  },
  { timestamps: true }
);

// Useful for the admin revenue dashboard's "successful payments by day".
paymentSchema.index({ status: 1, paidAt: -1 });
paymentSchema.index({ status: 1, expiresAt: 1 });
// Helps "did this user already pay for this design recently?" lookups
// without a full collection scan.
paymentSchema.index({ userId: 1, templateId: 1, status: 1, paidAt: -1 });

export type PaymentDoc = InferSchemaType<typeof paymentSchema> & {
  _id: mongoose.Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
};

export const Payment: Model<PaymentDoc> =
  (mongoose.models.Payment as Model<PaymentDoc>) ||
  mongoose.model<PaymentDoc>("Payment", paymentSchema);
