import mongoose, { Schema, type InferSchemaType, type Model } from "mongoose";

/**
 * One row per payment attempt. Created in `pending` state when the user opens
 * the Paystack popup; promoted to `success` after server-side verification
 * against Paystack's API (popup callback OR webhook - whichever lands first
 * wins, the other becomes a no-op via the unique reference).
 *
 * Lifecycle:
 *   pending  → success         (verified, grant issued)
 *   pending  → failed          (Paystack returned non-success on verify)
 *   pending  → abandoned       (user closed popup; cleaned up by ops job)
 *
 * The `paystackReference` is generated by us on init (so we can persist before
 * the network call) and echoed back to Paystack as `reference`. Unique index
 * is the idempotency anchor for verify + webhook.
 */
const paymentSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    templateId: {
      type: Schema.Types.ObjectId,
      ref: "Template",
      required: true,
      index: true,
    },
    // The user's working-design id (IndexedDB record id) - denormalised so
    // analytics can group "paid downloads of design X by user Y" without
    // joining IDB state. Optional so the schema doesn't lock us out of future
    // template-only purchases.
    userDesignId: { type: String, default: null },

    // Stored in kobo (Paystack's smallest unit). Converted to NGN at the
    // boundary. Centralises the precision discipline that prevents the
    // "100 NGN became 1.00 NGN" bug.
    amountKobo: { type: Number, required: true, min: 1 },
    currency: { type: String, default: "NGN" },

    // Our own reference, generated server-side at init. Globally unique.
    paystackReference: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    status: {
      type: String,
      enum: ["pending", "success", "failed", "abandoned"],
      default: "pending",
      required: true,
      index: true,
    },

    // The full Paystack verify payload - kept verbatim so reconciliation,
    // refund operations, and dispute handling have the original facts.
    providerResponse: { type: Schema.Types.Mixed, default: null },

    initializedAt: { type: Date, default: () => new Date() },
    paidAt: { type: Date, default: null },
    failedAt: { type: Date, default: null },
    failureReason: { type: String, default: null },
  },
  { timestamps: true }
);

// Useful for the admin revenue dashboard's "successful payments by day".
paymentSchema.index({ status: 1, paidAt: -1 });
// Helps "did this user already pay for this design recently?" lookups
// without a full collection scan.
paymentSchema.index({ userId: 1, templateId: 1, status: 1, paidAt: -1 });

export type PaymentDoc = InferSchemaType<typeof paymentSchema> & {
  _id: mongoose.Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
};

export const Payment: Model<PaymentDoc> =
  (mongoose.models.Payment as Model<PaymentDoc>) ||
  mongoose.model<PaymentDoc>("Payment", paymentSchema);
