export const DEPARTMENT_SEED = [
  "Computer Science",
  "Software Engineering",
  "Electrical and Electronic Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Mass Communication",
  "Accounting",
  "Banking and Finance",
  "Business Administration",
  "Economics",
  "Law",
  "Medicine and Surgery",
  "Nursing",
  "Pharmacy",
  "Architecture",
  "Estate Management",
  "Political Science",
  "Sociology",
  "Psychology",
  "English Language",
  "History",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Microbiology",
  "Biochemistry",
] as const;
